#!/usr/bin/env bash
# Publish the Godot runtime files into a target game repo.
#
# Usage:
#   ./publish.sh --agent claude|codex|opencode|omp --out <dir> [--force]
#   ./publish.sh --agent claude|codex|opencode|omp <dir> [--force]
#
# A published repo carries only docs: the runtime manifest (CLAUDE.md / AGENTS.md),
# the engine guide (godot.md), and the asset-gen skill. The agent scaffolds the
# game itself from the engine guide — no project scaffold is shipped.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
HELPERS="$REPO_ROOT/scripts"

AGENT=""
OUT=""
FORCE=0

usage() {
    sed -n '1,10p' "$0" >&2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --agent) AGENT="${2:-}"; shift 2 ;;
        --out)   OUT="${2:-}";   shift 2 ;;
        --force) FORCE=1;        shift   ;;
        -h|--help) usage; exit 0 ;;
        -*) echo "error: unknown option $1" >&2; usage; exit 1 ;;
        *)
            if [ -n "$OUT" ]; then
                echo "error: target specified more than once" >&2
                exit 1
            fi
            OUT="$1"
            shift
            ;;
    esac
done

case "$AGENT" in
    claude)
        MANIFEST="CLAUDE.md"
        SKILLS_DIR_REL=".claude/skills"
        AGENT_NAME="Claude"
        ASSET_SKILL_COMMAND="/asset-gen"
        ;;
    codex)
        MANIFEST="AGENTS.md"
        SKILLS_DIR_REL=".agents/skills"
        AGENT_NAME="Codex"
        ASSET_SKILL_COMMAND="\$asset-gen"
        ;;
    opencode)
        MANIFEST="AGENTS.md"
        SKILLS_DIR_REL=".opencode/skills"
        AGENT_NAME="OpenCode"
        ASSET_SKILL_COMMAND="the \"asset-gen\" skill"
        ;;
    omp)
        MANIFEST="AGENTS.md"
        SKILLS_DIR_REL=".omp/skills"
        AGENT_NAME="OMP"
        ASSET_SKILL_COMMAND="skill://asset-gen"
        ;;
    *) echo "error: --agent must be claude, codex, opencode, or omp" >&2; usage; exit 1 ;;
esac

ENGINE_GUIDE_FILE="godot.md"
# Root for runtime-loaded generated assets, substituted into the asset docs.
RUNTIME_ASSET_DIR="assets"

if [ -z "$OUT" ]; then
    echo "error: --out <target_dir> is required" >&2
    usage
    exit 1
fi

TARGET="$(cd "$OUT" 2>/dev/null && pwd || (mkdir -p "$OUT" && cd "$OUT" && pwd))"

if [ "$FORCE" -eq 1 ] && [ -d "$TARGET" ]; then
    echo "Force: cleaning $TARGET"
    rm -rf "${TARGET:?}"
    mkdir -p "$TARGET"
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Publishing godot/$AGENT to: $TARGET"

# --- Skills: only the asset-gen skill ---
mkdir -p "$TMP/skills/asset-gen"
rsync -a --delete --exclude='__pycache__/' "$REPO_ROOT/asset-gen/" "$TMP/skills/asset-gen/"

python3 "$HELPERS/render_dir.py" "$TMP/skills" \
    "AGENT_NAME=$AGENT_NAME" \
    "ASSET_GEN_SKILL_DIR=$SKILLS_DIR_REL/asset-gen" \
    "ASSET_SKILL_COMMAND=$ASSET_SKILL_COMMAND" \
    "RUNTIME_ASSET_DIR=$RUNTIME_ASSET_DIR"

if [ "$AGENT" = "codex" ]; then
    python3 "$HELPERS/generate_codex_metadata.py" "$TMP/skills"
fi

mkdir -p "$TARGET/$SKILLS_DIR_REL"
rsync -a --delete "$TMP/skills/" "$TARGET/$SKILLS_DIR_REL/"
echo "Installed asset-gen skill -> $SKILLS_DIR_REL"

# --- Manifest: the runtime process doc ---
MANIFEST_TMP="$TMP/manifest"
mkdir -p "$MANIFEST_TMP"
cp "$REPO_ROOT/prompts/runtime.md" "$MANIFEST_TMP/$MANIFEST"
python3 "$HELPERS/render_dir.py" "$MANIFEST_TMP" \
    "ASSET_SKILL_COMMAND=$ASSET_SKILL_COMMAND"
cp "$MANIFEST_TMP/$MANIFEST" "$TARGET/$MANIFEST"
echo "Created $MANIFEST"

# --- Engine guide (literal markdown) ---
cp "$REPO_ROOT/engines/godot.md" "$TARGET/$ENGINE_GUIDE_FILE"
echo "Created $ENGINE_GUIDE_FILE"

# --- Bridge script (drive-able game out of the box; a user file, never clobber) ---
if [ ! -f "$TARGET/scripts/Bridge.gd" ]; then
    mkdir -p "$TARGET/scripts"
    cp "$REPO_ROOT/engines/Bridge.gd" "$TARGET/scripts/Bridge.gd"
    echo "Created scripts/Bridge.gd"
fi

# --- .gitignore (published instruction files are regenerated by publish.sh) ---
GITIGNORE_ADD="$TMP/gitignore-add"
{
    case "$AGENT" in
        claude)   printf '.claude\nCLAUDE.md\n' ;;
        codex)    printf '.agents\nAGENTS.md\n.codex\n' ;;
        opencode) printf '.opencode\nAGENTS.md\n' ;;
        omp)      printf '.omp\nAGENTS.md\n' ;;
    esac
    printf '%s\n' "$ENGINE_GUIDE_FILE"
    printf 'assets\nscreenshots\n.godot\n*.import\nbin/\nobj/\n'
} > "$GITIGNORE_ADD"

if [ ! -f "$TARGET/.gitignore" ]; then
    cp "$GITIGNORE_ADD" "$TARGET/.gitignore"
    echo "Created .gitignore"
else
    while IFS= read -r line; do
        grep -qxF "$line" "$TARGET/.gitignore" || printf '%s\n' "$line" >> "$TARGET/.gitignore"
    done < "$GITIGNORE_ADD"
    echo "Updated .gitignore"
fi

git -C "$TARGET" init -q 2>/dev/null || true

echo "Done."
